### ISSUE TITLE
Reset conversation history

### ISSUE THREAD

**Issue by ThatcherC** [ThatcherC/ReplGPT.jl#18]
Implement a way to clear out the ChatGPT history so a new conversation can be started.

**Comment by diegozea** [comment]
That's delete (d) in my list of commands as I have used r for regenerate: https://github.com/ThatcherC/ReplGPT.jl/issues/17#issue-1632760787

**Comment by ThatcherC** [comment]
Yup! Should be a quick change, just tracking it here for now. I think what'll happen is I'll write a regular Julia function to clear out the conversation history first, and then later hook it into a command system like @diegozea's - I like that interface too.

**Comment by ThatcherC** [comment]
Address in #21! The conversation can now be reset with `ReplGPT.initialize_conversation()`. Next up will be putting together something like @diegozea's cool command interface so the conversation can be reset from within the `ChatGPT>` shell.
